language: python

stages:
  - linting
  - test
  - codecov

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

before_install:
  - sudo apt-get install -y libev-dev

install:
  - pip install pip==18.1
  - pip install poetry
  - poetry install -v

script: pytest -q tests/

jobs:
  include:
    - python: "3.7"
    - python: "3.8"

    - stage: linting
      python: "3.7"
      install:
        - pip install black
        - pip install mypy
      script:
        - black .
        - mypy .
    - stage: codecov
      python: "3.7"
      script:
        - pytest --ignore venv -W ignore::DeprecationWarning --cov=kink tests --cov-report=term-missing
        - pip install codecov
        - codecov
