[tool.poetry]
name = "kink"
version = "0.1.1"
description = "Dependency injection for python."
authors = [
    "Dawid Kraczkowski <dawid.kraczkowski@gmail.com>"
]
license = "MIT"
readme = "README.md"

keywords = ["kink", "dependency injection"]

homepage = "https://github.com/kodemore/kink"
repository = "https://github.com/kodemore/kink"
documentation = "https://github.com/kodemore/kink"

classifiers = [
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

# Requirements
[tool.poetry.dependencies]
python = "^3.7"
typing_extensions = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^4.1.0"
pytest-cov = "^2.5"
mypy = "^0.730.0"
black = { version = "^19.3b0", python = "^3.6" }

